name: Integration Tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: [ "main", "dev"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  MOOSE:
    runs-on: ubuntu-latest
    container:
      image: idaholab/moose:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          useradd -g root -m dev; su - dev; python -m pip install poetry; export PATH=/opt/openmpi/bin:$PATH; export SIMVUE_URL=${{ secrets.SIMVUE_URL }}; export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}; poetry install --with dev; whoami; pwd; poetry run pytest tests/integration/test_moose.py